server:
  port: 8769

zuul:
  routes:
    apollo-config:
      path: /apollo-config/**
      serviceId: apollo-config
    stream-rabbitmq:
      path: /stream-rabbitmq/**
      serviceId: stream-rabbitmq

logging:
  path: logs
